# Generated by Django 4.2 on 2025-02-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entity Types',
                'db_table': 'entity_type',
            },
        ),
        migrations.CreateModel(
            name='PlantEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uid', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.entitytype')),
            ],
            options={
                'verbose_name_plural': 'Plant Entities',
                'db_table': 'plant_entity',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=255, unique=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=50)),
                ('default_language', models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the filter is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tenants',
                'db_table': 'wa_tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantStorageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(choices=[('azure', 'Azure'), ('aws', 'AWS'), ('gcp', 'GCP')], max_length=100)),
                ('account_name', models.CharField(help_text='Storage Account Name', max_length=255)),
                ('account_key', models.CharField(blank=True, help_text='Storage Account Key or equivalent', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='storage_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Tenant Storage Settings',
                'db_table': 'tenant_storage_settings',
            },
        ),
        migrations.CreateModel(
            name='SensorBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_box_name', models.CharField(max_length=255)),
                ('sensor_box_location', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('plant_entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.plantentity')),
            ],
            options={
                'verbose_name_plural': 'Sensor Boxes',
                'db_table': 'sensor_box',
                'unique_together': {('plant_entity', 'sensor_box_name')},
            },
        ),
        migrations.AddField(
            model_name='entitytype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=255)),
                ('camera_position', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='tenants.sensorbox')),
            ],
            options={
                'verbose_name_plural': 'Cameras',
                'db_table': 'cameras',
                'unique_together': {('sensor_box', 'camera_id')},
            },
        ),
    ]
