version: '3.3'

services:
  # core
  video-buffer-core:
    image: tannous/tannous:video-buffer-ubuntu.20.04
    container_name: video-buffer-core
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      args:
        user: ${user}
        userid: ${userid}
        group: ${group}
        groupid: ${groupid}
    networks:
      - internal
    ports:
      - ${INET_HTTP_SERVER_PORT}:${INET_HTTP_SERVER_PORT}
      - ${EVENT_API_PORT}:${EVENT_API_PORT}
      - ${DJANGO_ADMIN_PORT}:${DJANGO_ADMIN_PORT}
      - ${FLOWER_PORT}:${FLOWER_PORT}
      - ${DATA_API_PORT}:${DATA_API_PORT}
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/home/$user/src
      - /home/tannous/Desktop/ros2_bags:/media
    user: ${user}

  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: video-buffer-rabbitmq
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - internal
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  postgres:
    image: postgres:latest
    container_name: video-buffer-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
    networks:
     - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # ros2_bag:
  #   image: tannousgeagea/ros2:humble-desktop
  #   container_name: ros2_bag_player
  #   stdin_open: true
  #   tty: true
  #   networks: 
  #     - internal
  #   volumes:
  #     - /home/tannous/Downloads/rosbag2_2025_03_04-09_51_15:/rosbags
  #   command: ["ros2", "bag", "play", "/rosbags/rosbag2_2025_03_04-09_51_15_0.db3", '--loop']

networks:
  internal:
    driver: bridge

volumes:
  media:
  postgres_data:
