# Generated by Django 4.2 on 2025-02-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='images_used',
            field=models.ManyToManyField(related_name='videos', to='media.image'),
        ),
    ]
