# Generated by Django 4.2 on 2026-04-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_video_images_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='frame_manifest',
            field=models.JSONField(blank=True, help_text='Inline frame→wall-time manifest. Kept in sync with manifest_url.', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='framerate',
            field=models.FloatField(blank=True, help_text='Playback framerate of the encoded video file.', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='manifest_url',
            field=models.URLField(blank=True, help_text='Cloud storage URL for the sidecar manifest JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the encoded video file. Typically much shorter than the real-world recording session.', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Wall-clock UTC end time of the recording session. Represents the real-world time when the last frame was captured.', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Wall-clock UTC start time of the recording session. Represents the real-world time when the first frame was captured.', null=True),
        ),
    ]
