# Generated by Django 4.2 on 2024-10-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
            },
        ),
        migrations.RenameIndex(
            model_name='filterlocalization',
            new_name='filter_loca_filter__f6b872_idx',
            old_name='filter_loca_filter__f28b99_idx',
        ),
        migrations.RenameIndex(
            model_name='metadatalocalization',
            new_name='metadata_lo_metadat_42e838_idx',
            old_name='metadata_lo_metadat_651cbe_idx',
        ),
        migrations.AlterField(
            model_name='filterlocalization',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.language'),
        ),
        migrations.AlterField(
            model_name='metadatalocalization',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.language'),
        ),
    ]
