# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_acquisition.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data_acquisition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x61ta_acquisition.proto\x12\x10\x64\x61ta_acquisition\"\"\n\x12ProcessDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"%\n\x13ProcessDataResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2m\n\rComputingUnit\x12\\\n\x0bProcessData\x12$.data_acquisition.ProcessDataRequest\x1a%.data_acquisition.ProcessDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_acquisition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSDATAREQUEST']._serialized_start=44
  _globals['_PROCESSDATAREQUEST']._serialized_end=78
  _globals['_PROCESSDATARESPONSE']._serialized_start=80
  _globals['_PROCESSDATARESPONSE']._serialized_end=117
  _globals['_COMPUTINGUNIT']._serialized_start=119
  _globals['_COMPUTINGUNIT']._serialized_end=228
# @@protoc_insertion_point(module_scope)
