"""
Django settings for video_buffer project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3pmw%smn(bh#a9tsw12+=@3&hk*grraq7!s1t$9q6#41ck=1qf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [os.getenv('ALLOWED_HOST', '0.0.0.0')]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'tenants',
    'metadata',
    'configure',
    'media',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'video_buffer.urls'
AUTH_USER_MODEL = "users.CustomUser"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'video_buffer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE', "django.db.backends.sqlite3"),
        'NAME': os.environ.get('DATABASE_NAME') if not 'sqlite3' in os.environ.get('DATABASE_ENGINE') else BASE_DIR / 'db.sqlite3',
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': os.environ.get('DATABASE_PORT')

    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "media/"
MEDIA_ROOT = "/media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_HEADER": _("Video Archive App"),
    "SITE_TITLE": _("Video Archive"),
    "SITE_SYMBOL": "switch_video",
    # "SITE_LOGO": {
    #     "light": lambda r: static("wa-logo-green.png"),  # light mode
    #     "dark": lambda r: static("wa-logo-white.png"),  # dark mode
    # },
    # "LOGIN": {
    #     "image": lambda r: static("login-bg.png"),
    #     # "redirect_after": lambda r: reverse_lazy("admin:APP_MODEL_changelist"),
    # },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "items": [
                    {
                        "title": _("All Apps"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ]
            },
            {
                "title": _("Tenants"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Tenant"),
                        "icon": 'tenancy',
                        "link": reverse_lazy(
                            "admin:tenants_tenant_changelist"
                        ),
                    },
                    {
                        "title": _("Entity"),
                        "icon": 'fingerprint',
                        "link": reverse_lazy(
                            "admin:tenants_entitytype_changelist"
                        ),
                    },
                    {
                        "title": _("Tenant Entity"),
                        "icon": 'type_specimen',
                        "link": reverse_lazy(
                            "admin:tenants_plantentity_changelist"
                        ),
                    },
                    {
                        "title": _("SensorBoxes"),
                        "icon": 'sensors',
                        "link": reverse_lazy(
                            "admin:tenants_sensorbox_changelist"
                        ),
                    },
                    {
                        "title": _("Cameras"),
                        "icon": 'videocam',
                        "link": reverse_lazy(
                            "admin:tenants_camera_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("Users & Groups"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy(
                            "admin:users_customuser_changelist"
                            ),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy(
                            "admin:auth_group_changelist"
                            ),
                    }
                ],
            },
            {
                "title": _("Configuration"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("App config"),
                        "icon": 'settings',
                        "link": reverse_lazy(
                            "admin:configure_appconfig_changelist"
                        ),
                    },
                    {
                        "title": _("Data Sources"),
                        "icon": 'frame_source',
                        "link": reverse_lazy(
                            "admin:configure_datasource_changelist"
                        ),
                    },
                    {
                        "title": _("Data Aquicistion Config"),
                        "icon": 'topic',
                        "link": reverse_lazy(
                            "admin:configure_dataacquisitionconfig_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("MetaData"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Languages"),
                        "icon": "language",
                        "link": reverse_lazy(
                            "admin:metadata_language_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Media"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Images"),
                        "icon": "image",
                        "link": reverse_lazy(
                            "admin:media_image_changelist"
                        ),
                    },
                    {
                        "title": _("Videos"),
                        "icon": "play_arrow",
                        "link": reverse_lazy(
                            "admin:media_video_changelist"
                        ),
                    },
                ],
            },
        ],
    },
}