# Generated by Django 4.2 on 2025-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='message_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
